# Generated by Django 4.1.4 on 2022-12-25 07:24

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_rename_text_comment_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=20)),
                ('pw', models.CharField(max_length=20)),
                ('Create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('phone_num', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
            ],
        ),
    ]
