# Generated by Django 4.1.4 on 2022-12-30 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Create_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_num',
        ),
    ]
