# Generated by Django 4.1.4 on 2022-12-20 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2022, 12, 20, 12, 54, 35, 868659, tzinfo=datetime.timezone.utc))),
                ('update_date', models.DateTimeField(default=datetime.datetime(2022, 12, 20, 12, 54, 35, 868659, tzinfo=datetime.timezone.utc))),
                ('content', models.TextField()),
                ('img', models.ImageField(blank=True, upload_to='media/')),
            ],
        ),
    ]
