# Generated by Django 4.1.4 on 2022-12-22 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 22, 5, 58, 11, 112989, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='article',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 22, 5, 58, 11, 112989, tzinfo=datetime.timezone.utc)),
        ),
    ]
